export const CHANGE_SELECTEDID = 'CHANGE_SELECTEDID'
export const CHANGE_DEPT_LIST = 'CHANGE_DEPT_LIST'
export const CHANGE_STAFF_LIST = 'CHANGE_STAFF_LIST'
export const CHANGE_CONTACT_PAGENO = 'CHANGE_CONTACT_PAGENO'
export const CHANGE_CONTACT_PAGESIZE = 'CHANGE_CONTACT_PAGESIZE'
export const CHANGE_APPROVE_TREE_SELECTED="CHANGE_APPROVE_TREE_SELECTED"
// 待我审批数目
export const SET_WAIT_APPROVE_NUM="SET_WAIT_APPROVE_NUM"