module.exports = {
	"/api/*": "/$1",
	"/v1/dept/list*": "/contactdeptlist$1",
	"/v1/staff/list*": "/contactstafflist$1",
	"/v1/staff/detail*": "/contactstaffdetail$1",
	"/v1/user/user_info*": "/userInfo$1",
	"/v1/access_authorize*":"/accessAuthorize$1",
	"/notice/queryUserNoticeMsgCount*": '/noticeNum$1',
	"/v1/logout*": "/logout$1",
   "/approve/myTasks*":"/approveWaitlist$1",
   "/approve/myFinishedTask*":"/approveFinshedlist$1",
   "/approve/list*":"/myApprove$1",
	"/v1/staff/detail*": "/userDetail$1",
	"/approve/act/view*": "/approveFormFlows$1",
	"/approve/approveForms/view*": "/approveFormElements$1",
   "/notice/queryNoticeStaffInfo*": "/noticeList$1",
   "/notice/queryUserNoticeById/*": "/noticeDetail",
   "/notice/collectNotice/*": "/noticeList/$1",
	"/v1/common/baseDeptInfos*": "/baseStaffInfos$1",
	"/v1/common/lightList*": "/lightList$1",
	"/approve/view*" : "/viewFormData$1",
	"/approve/myApproveCount*" : "/myApproveCount$1",
	"/approve/setting/flow/list*" : "/flowList$1",
	"/approve/add": "/newSaveApproveObj"
}